version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/backend/Dockerfile.dev
    image: dfgdp-webapp-backend:latest
    ports:
      - "5073:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dfgdp_webapp
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-here
      - JWT_SECRET_KEY=your-jwt-secret-here
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile.dev
    image: dfgdp-webapp-frontend:latest
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5073
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dfgdp_webapp
    ports:
      - "5473:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6373:6379"

  worker:
    build:
      context: ./backend
      dockerfile: docker/backend/Dockerfile.dev
    image: dfgdp-webapp-worker:latest
    depends_on:
      - redis
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/dfgdp_webapp
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-here
      - JWT_SECRET_KEY=your-jwt-secret-here
    command: >
      watchmedo auto-restart 
      --directory=./src 
      --pattern="*.py" 
      --recursive 
      -- 
      python -m tasks.worker
    volumes:
      - ./backend:/app

volumes:
  postgres_data: