INITIAL_TAGS = [
    "piracy",
    "slavery",
    "carnival",
    "festivals",
    "cuisine",
    "agriculture",
    "immigration",
    "colonial architecture",
    "canal treaties",
    "Spanish colonization",
    "Pre-Columbian civilizations",
    "independence",
    "coffee",
    "traditional music",
    "traditional dance",
    "urban development",
    "Afro-Latin music",
    "Chinese diaspora",
    "indigenous autonomy",
    "molas",
    "pollera",
    "Rubén Blades",
    "Omar Torrijos",
    "yellow fever",
    "Darién Gap",
    "Portobelo",
    "Panamá Viejo",
    "Casco Viejo",
    "canal zone",
    "Manuel Noriega",
    "migration routes",
    "economics",
    "U.S. intervention",
    "Torrijos-Carter treaties",
    "artisanal crafts",
    "ecotourism",
    "Congo culture",
    "catholic church",
    "protestant missions",
    "transisthmian railroad",
    "banana plantations",
    "típico music",
    "cimarron communities",
    "Panamanian diaspora",
    "biodiversity",
    "maritime trade",
    "tropical climate",
    "sancocho",
    "urban sprawl",
    "canal expansion",
]
