INITIAL_HASHTAG_GROUPS = [
    {
        "name": "Core Brand",
        "description": "Core hashtags that represent our brand and main themes. Used in all posts.",
        "is_core": True,
        "hashtags": [
            "PanamaInContext",
            "Panama",
            "DiscoverPanama",
            "PanamaHistory",
            "PanamaCulture",
            "PanamaEducation",
            "CulturalHeritage",
        ],
    },
    {
        "name": "Panama Canal",
        "description": "Hashtags for content related to the Panama Canal, its construction, and impact.",
        "is_core": False,
        "hashtags": [
            "PanamaCanal",
            "CanalDePanama",
            "CanalHistory",
            "PanamaCanalHistory",
            "CanalZone",
            "MaritimeHistory",
            "GlobalTrade",
        ],
    },
    {
        "name": "Indigenous Heritage",
        "description": "Hashtags for content about Panama's indigenous peoples and their cultures.",
        "is_core": False,
        "hashtags": [
            "GunaYala",
            "Ngäbe",
            "Buglé",
            "Emberá",
            "Wounaan",
            "IndigenousPanama",
            "IndigenousCulture",
            "NativePeoples",
        ],
    },
    {
        "name": "Colonial Period",
        "description": "Hashtags for colonial era content and Spanish influence.",
        "is_core": False,
        "hashtags": [
            "ColonialPanama",
            "SpanishColonial",
            "ColonialHistory",
            "CascoViejo",
            "ColonialArchitecture",
            "SpanishEmpire",
        ],
    },
    {
        "name": "Cultural Diversity",
        "description": "Hashtags highlighting Panama's multicultural heritage.",
        "is_core": False,
        "hashtags": [
            "MulticulturalPanama",
            "PanamanianCulture",
            "AfroAntillean",
            "ChinesePanama",
            "WestIndian",
            "CulturalDiversity",
            "PanamaTraditions",
        ],
    },
    {
        "name": "Education",
        "description": "Education-focused hashtags for academic and learning content.",
        "is_core": False,
        "hashtags": [
            "HistoryEducation",
            "LearnHistory",
            "HistoryTeacher",
            "EducaciónPanamá",
            "HistoriaDeParamá",
            "TeachingHistory",
            "HistoryResources",
        ],
    },
]
