"""Add support for article series

Revision ID: 0bf868942dc0
Revises: 0c5b33832103
Create Date: 2025-01-13 01:20:07.971626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0bf868942dc0"
down_revision = "0c5b33832103"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "series_order",
                sa.Integer(),
                nullable=True,
                comment="Order in article series, null if standalone",
            )
        )
        batch_op.add_column(
            sa.Column(
                "series_parent_id",
                sa.Integer(),
                nullable=True,
                comment="First article in the series",
            )
        )
        batch_op.create_index(
            "idx_article_series", ["series_parent_id", "series_order"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_articles_series_parent_id"),
            ["series_parent_id"],
            unique=False,
        )
        # Specify a name for the foreign key constraint
        batch_op.create_foreign_key(
            "fk_articles_series_parent",
            "articles",
            ["series_parent_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles", schema=None) as batch_op:
        # Use the specified name to drop the foreign key constraint
        batch_op.drop_constraint("fk_articles_series_parent", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_articles_series_parent_id"))
        batch_op.drop_index("idx_article_series")
        batch_op.drop_column("series_parent_id")
        batch_op.drop_column("series_order")

    # ### end Alembic commands ###
