"""include ai generation mixin in translations

Revision ID: 0c5b33832103
Revises: 4be9b7ca25ac
Create Date: 2024-12-16 20:09:41.469399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0c5b33832103"
down_revision = "4be9b7ca25ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("translations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tokens_used", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "generation_started_at", sa.DateTime(timezone=True), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("last_generation_error", sa.Text(), nullable=True)
        )
        batch_op.add_column(sa.Column("model_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_translations_model_id"), ["model_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_translations_model_id",  # Explicit name for the foreign key
            "ai_models",
            ["model_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("translations", schema=None) as batch_op:
        batch_op.drop_constraint("fk_translations_model_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_translations_model_id"))
        batch_op.drop_column("model_id")
        batch_op.drop_column("last_generation_error")
        batch_op.drop_column("generation_started_at")
        batch_op.drop_column("tokens_used")

    # ### end Alembic commands ###
