"""update media and social media post models

Revision ID: 22ffedff2377
Revises: 3b676f0c9dc0
Create Date: 2024-12-13 23:05:06.999355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "22ffedff2377"
down_revision = "3b676f0c9dc0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE instagram_media_type AS ENUM ('SQUARE', 'PORTRAIT', 'LANDSCAPE', 'STORY', 'REEL')"
    )

    op.create_table(
        "social_media_post_media",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            comment="Order position in carousel, starting from 0",
        ),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["post_id"], ["social_media_posts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("post_id", "media_id"),
    )
    with op.batch_alter_table("social_media_post_media", schema=None) as batch_op:
        batch_op.create_index(
            "idx_social_media_post_media_position", ["post_id", "position"], unique=True
        )
        batch_op.create_index(
            "idx_social_media_post_media_post", ["post_id"], unique=False
        )

    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.add_column(sa.Column("width", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("height", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "instagram_media_type",
                sa.Enum(
                    "SQUARE",
                    "PORTRAIT",
                    "LANDSCAPE",
                    "STORY",
                    "REEL",
                    name="instagram_media_type",
                ),
                nullable=True,
            )
        )

    with op.batch_alter_table("social_media_posts", schema=None) as batch_op:
        batch_op.drop_constraint("social_media_posts_image_id_fkey", type_="foreignkey")
        batch_op.drop_column("image_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("social_media_posts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("image_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            "social_media_posts_image_id_fkey",
            "media",
            ["image_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.drop_column("instagram_media_type")
        batch_op.drop_column("height")
        batch_op.drop_column("width")

    with op.batch_alter_table("social_media_post_media", schema=None) as batch_op:
        batch_op.drop_index("idx_social_media_post_media_post")
        batch_op.drop_index("idx_social_media_post_media_position")

    op.drop_table("social_media_post_media")

    # Drop the enum type
    op.execute("DROP TYPE instagram_media_type")
    # ### end Alembic commands ###
