"""Make main_topic and sub_topics nullable

Revision ID: 3dbe9592fb5f
Revises: 8028819c3cc6
Create Date: 2025-01-25 22:43:46.924195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3dbe9592fb5f"
down_revision = "8028819c3cc6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("article_suggestions", schema=None) as batch_op:
        batch_op.alter_column("main_topic", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "sub_topics",
            existing_type=postgresql.ARRAY(sa.VARCHAR(length=255)),
            nullable=True,
            existing_server_default=sa.text("ARRAY[]::character varying[]"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("article_suggestions", schema=None) as batch_op:
        batch_op.alter_column(
            "sub_topics",
            existing_type=postgresql.ARRAY(sa.VARCHAR(length=255)),
            nullable=False,
            existing_server_default=sa.text("ARRAY[]::character varying[]"),
        )
        batch_op.alter_column("main_topic", existing_type=sa.TEXT(), nullable=False)

    # ### end Alembic commands ###
