"""add post types to social media posts

Revision ID: 4d275a2b3523
Revises: 22ffedff2377
Create Date: 2024-12-13 23:55:32.704680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d275a2b3523'
down_revision = '22ffedff2377'
branch_labels = None
depends_on = None


def upgrade():
    # Create the enum type first
    op.execute("CREATE TYPE post_type AS ENUM ('FEED', 'STORY')")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media_posts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('post_type', sa.Enum('FEED', 'STORY', name='post_type'), server_default=sa.text("'FEED'"),
                      nullable=False))
        batch_op.add_column(sa.Column('is_highlight', sa.Boolean(), server_default=sa.text('false'), nullable=False,
                                      comment='Whether this story is saved as a highlight'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media_posts', schema=None) as batch_op:
        batch_op.drop_column('is_highlight')
        batch_op.drop_column('post_type')

    # Drop the enum type
    op.execute('DROP TYPE post_type')
    # ### end Alembic commands ###
