"""Add rate columns to ai_models

Revision ID: 85f70508cd6d
Revises: c146f62412c6
Create Date: 2024-12-10 19:24:30.181951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "85f70508cd6d"
down_revision = "c146f62412c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_models", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("input_rate", sa.DECIMAL(precision=10, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "batch_input_rate", sa.DECIMAL(precision=10, scale=2), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("output_rate", sa.DECIMAL(precision=10, scale=2), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "batch_output_rate", sa.DECIMAL(precision=10, scale=2), nullable=True
            )
        )

    with op.batch_alter_table("article_relationships", schema=None) as batch_op:
        batch_op.drop_constraint(
            "article_relationships_article_id_fkey", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "article_relationships_related_article_id_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "articles", ["related_article_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            None, "articles", ["article_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("article_relationships", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "article_relationships_related_article_id_fkey",
            "articles",
            ["related_article_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "article_relationships_article_id_fkey", "articles", ["article_id"], ["id"]
        )

    with op.batch_alter_table("ai_models", schema=None) as batch_op:
        batch_op.drop_column("batch_output_rate")
        batch_op.drop_column("output_rate")
        batch_op.drop_column("batch_input_rate")
        batch_op.drop_column("input_rate")

    # ### end Alembic commands ###
