"""implement hash tag groups

Revision ID: 8e2bd2320dbe
Revises: 4d275a2b3523
Create Date: 2024-12-14 13:50:39.044102

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8e2bd2320dbe"
down_revision = "4d275a2b3523"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hashtag_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "hashtags",
            sa.ARRAY(sa.String(length=100)),
            server_default=sa.text("ARRAY[]::varchar[]"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "is_core",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Whether this is a core group that should be included in all posts",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="Predefined groups of hashtags for social media posts",
    )
    with op.batch_alter_table("hashtag_groups", schema=None) as batch_op:
        batch_op.create_index("idx_hashtag_group_core", ["is_core"], unique=False)
        batch_op.create_index("idx_hashtag_group_name", ["name"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hashtag_groups", schema=None) as batch_op:
        batch_op.drop_index("idx_hashtag_group_name")
        batch_op.drop_index("idx_hashtag_group_core")

    op.drop_table("hashtag_groups")
    # ### end Alembic commands ###
